USE cull_dampolla;
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Sera Martin","C/ Del Mar",25,1,"A","Moncofa","12593","ES","666069069","923564825","mailito@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Alberto Jambo","C/ Pino",12,12,"2","A Coruña","25632","ES","666662665","934382561","correito@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Nuria Peig","C/ Puente",1,2,"Z","Badalona","23563","UK","612345678","923256987","mensajin@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Maria Marcia","C/ Atolon",17,1,"A","Sitges","12953","ES","555555555","912365489","chivatin@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Juanito Pellas","C/ Del Mar",3,1,"B","Moncofa","12593","ES","666222333","912334569","mirame@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Lucia Serrano","C/ Barnatxo",11,3,"D","Soria","21564","ES","666225339","945698712","falso@mail.mal");
INSERT INTO personas(personas_nombre, personas_calle,personas_num,personas_piso,personas_puerta,personas_ciudad,personas_cp,personas_pais,personas_tel,personas_fax,personas_email ) VALUES("Ana Bolizante","C/ Del Mar",25,1,"A","Tarragona","12593","ES","999666999","912459786","nossisto@mail.mal");
INSERT INTO clientes(clientes_reg, personas_personas_id) VALUES("2020-01-02 09:00:00",1);
INSERT INTO clientes(clientes_reg, personas_personas_id) VALUES("2020-01-20 09:00:00",2);
INSERT INTO clientes(clientes_reg, personas_personas_id) VALUES("2020-02-02 09:00:00",3);
INSERT INTO clientes(clientes_reg, personas_personas_id) VALUES("2020-06-22 09:00:00",4);
INSERT INTO clientes(clientes_reg, personas_personas_id) VALUES("2020-11-12 09:00:00",5);
INSERT INTO proveedores(proveedores_nif,personas_personas_id) VALUES("12345678Y",6);
INSERT INTO proveedores(proveedores_nif,personas_personas_id) VALUES("23456789M",7);
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("Etnia Barcelona",1);
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("GUESS",1);
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("VOGUE",2);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id,clientes_clientes_id) VALUES ("00,25","azul","02,50","azul","3","azul","001",1,1);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id,clientes_clientes_id) VALUES ("15,00","rosa","15,00","rosa","1","verde","003",2,2);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id,clientes_clientes_id) VALUES ("00,05","traslucido","00,01","traslucido","2","negra","001",3,3);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id,clientes_clientes_id) VALUES ("00,75","amarillo","12,50","amarillo","1","lima","002",2,4);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id,clientes_clientes_id) VALUES ("00,25","rojo","02,50","rojo","3","fucsia","001",1,5);
