USE cull_dampolla;
INSERT INTO clientes(clientes_reg, clientes_nombre,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_ciudad,clientes_cp,clientes_pais,clientes_tel,clientes_fax,clientes_email) VALUES("2020-01-02 09:00:00","Sera","C/ Del Mar",25,1,"A","Moncofa","12593","ES","666069069","923564825","mailito@mail.mal");
INSERT INTO clientes(clientes_reg, clientes_nombre, clientes_recomendador, clientes_calle, clientes_num, clientes_piso, clientes_puerta, clientes_ciudad, clientes_cp, clientes_pais, clientes_tel, clientes_fax, clientes_email) VALUES("2020-01-20 09:00:00","Manolo",1,"C/ Pino",12,12,"2","A Coruña","25632","ES","666662665","934382561","correito@mail.mal" );
INSERT INTO clientes(clientes_reg, clientes_nombre, clientes_recomendador,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_ciudad,clientes_cp,clientes_pais,clientes_tel,clientes_fax,clientes_email) VALUES("2020-02-02 09:00:00","Eva",1, "C/ Puente",1,2,"Z","Badalona","23563","UK","612345678","923256987","mensajin@mail.mal");
INSERT INTO clientes(clientes_reg, clientes_nombre, clientes_recomendador,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_ciudad,clientes_cp,clientes_pais,clientes_tel,clientes_fax,clientes_email) VALUES("2020-06-22 09:00:00","Txema",1, "C/ Atolon",17,1,"A","Sitges","12953","ES","555555555","912365489","chivatin@mail.mal");
INSERT INTO clientes(clientes_reg, clientes_nombre, clientes_recomendador,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_ciudad,clientes_cp,clientes_pais,clientes_tel,clientes_fax,clientes_email) VALUES("2020-11-12 09:00:00","Pablo",1, "C/ Del Mar",3,1,"B","Moncofa","12593","ES","666222333","912334569","mirame@mail.mal");
INSERT INTO proveedores(proveedores_nif,proveedores_nombre,proveedores_calle,proveedores_num,proveedores_piso,proveedores_puerta,proveedores_ciudad,proveedores_cp,proveedores_pais,proveedores_tel,proveedores_fax,proveedores_email) VALUES("12345678Y","Ataulfo","C/ Barnatxo",11,3,"D","Soria","21564","ES","666225339","945698712","falso@mail.mal");
INSERT INTO proveedores(proveedores_nif,proveedores_nombre,proveedores_calle,proveedores_num,proveedores_piso,proveedores_puerta,proveedores_ciudad,proveedores_cp,proveedores_pais,proveedores_tel,proveedores_fax,proveedores_email) VALUES("23456789M","Chindasvinto", "C/ Del Mar",25,1,"A","Tarragona","12593","ES","999666999","912459786","nossisto@mail.mal");
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("Etnia Barcelona",1);
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("GUESS",1);
INSERT INTO marcas(marcas_nombre,proveedores_proveedores_id) VALUES("VOGUE",2);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id) VALUES ("00,25","azul","02,50","azul","3","azul","001",1);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id) VALUES ("15,00","rosa","15,00","rosa","1","verde","003",2);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id) VALUES ("00,05","traslucido","00,01","traslucido","2","negra","001",3);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id) VALUES ("00,75","amarillo","12,50","amarillo","1","lima","002",2);
INSERT INTO gafas(gafas_grad_izda,gafas_color_izda,gafas_grad_dcha,gafas_color_dcha,gafas_montura,gafas_color_montura,gafas_vendedor,marcas_marcas_id) VALUES ("00,25","rojo","02,50","rojo","3","fucsia","001",1);
INSERT INTO factura(factura_total,clientes_clientes_id) VALUES ("120",1);
INSERT INTO factura(factura_total,clientes_clientes_id) VALUES ("130",2);
INSERT INTO factura(factura_total,clientes_clientes_id) VALUES ("140",3);
INSERT INTO factura(factura_total,clientes_clientes_id) VALUES ("110",4);
INSERT INTO factura(factura_total,clientes_clientes_id) VALUES ("160",5);
INSERT INTO compra(compra_cantidad,gafas_gafas_id,factura_factura_id) VALUES (1,1,1);
INSERT INTO compra(compra_cantidad,gafas_gafas_id,factura_factura_id) VALUES (1,2,2);
INSERT INTO compra(compra_cantidad,gafas_gafas_id,factura_factura_id) VALUES (1,3,3);
INSERT INTO compra(compra_cantidad,gafas_gafas_id,factura_factura_id) VALUES (1,4,4);
INSERT INTO compra(compra_cantidad,gafas_gafas_id,factura_factura_id) VALUES (1,5,5);