USE pizzeria;
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Primavera",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Verano",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Otoño",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Invierno",1);
INSERT INTO provincias(provincias_nombre) VALUES("Barcelona");
INSERT INTO provincias(provincias_nombre) VALUES("Tarragona");
INSERT INTO provincias(provincias_nombre) VALUES("Lleida");
INSERT INTO provincias(provincias_nombre) VALUES("Girona");
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Badalona",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Hospitalet",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Barcelona",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Reus",2);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Tarragona",2);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Lleida",3);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Balaguer",3);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Figueres",4);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Girona",4);
INSERT INTO tiendas(tiendas_mat, tiendas_calle,tiendas_num,tiendas_piso,tiendas_puerta,tiendas_cp,localidades_localidades_id)VALUES("PIZ0001","C/Roma",1,"Bj","1",00001,9);
INSERT INTO tiendas(tiendas_mat, tiendas_calle,tiendas_num,tiendas_piso,tiendas_puerta,tiendas_cp,localidades_localidades_id)VALUES("PIZ0002","C/Napoles",1,"Bj","1",00001,6);
INSERT INTO tiendas(tiendas_mat, tiendas_calle,tiendas_num,tiendas_piso,tiendas_puerta,tiendas_cp,localidades_localidades_id)VALUES("PIZ0003","C/Sicilia",1,"Bj","1",00001,5);
INSERT INTO tiendas(tiendas_mat, tiendas_calle,tiendas_num,tiendas_piso,tiendas_puerta,tiendas_cp,localidades_localidades_id)VALUES("PIZ0004","C/Florencia",1,"Bj","1",00001,3);
INSERT INTO empleados(tiendas_tiendas_id,empleados_nombre,empleados_apellidos,empleados_tfno, empleados_calle, empleados_num,empleados_piso,empleados_puerta,empleados_cp,localidades_localidades_id)VALUES(1,"Maria","Antonia Gutierrez","666111111","C/Uno",12,"1","A",00001,1);
INSERT INTO empleados(tiendas_tiendas_id,empleados_nombre,empleados_apellidos,empleados_tfno, empleados_calle, empleados_num,empleados_piso,empleados_puerta,empleados_cp,localidades_localidades_id)VALUES(2,"Sera","Martin","666222111","C/Dos",13,"2","B",00002,2);
INSERT INTO empleados(tiendas_tiendas_id,empleados_nombre,empleados_apellidos,empleados_tfno, empleados_calle, empleados_num,empleados_piso,empleados_puerta,empleados_cp,localidades_localidades_id)VALUES(3,"Antonio","Safore","666333111","C/Tres",14,"3","B",00003,3);
INSERT INTO empleados(tiendas_tiendas_id,empleados_nombre,empleados_apellidos,empleados_tfno, empleados_calle, empleados_num,empleados_piso,empleados_puerta,empleados_cp,localidades_localidades_id)VALUES(4,"Pelusa","Gingientez","666444111","C/Cuatro",15,"4","1",00004,4);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Antonio","Safore","666333111","C/Tres",14,"3","B",00003,3);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Pelusa","Gingientez","666444111","C/Cuatro",15,"4","1",00004,4);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Jane","Doe","666555111","C/Cinco",16,"5","2",00005,5);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("John","Doe","666666111","C/Seis",12,"6","3",00006,6);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Teo","De Dios De Dios","666777111","C/Siete",17,"7","4",00007,7);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Juan","Martin","666888111","C/Ocho",18,"8","A",00008,8);
INSERT INTO clientes(clientes_nombre,clientes_apellidos,clientes_tfno,clientes_calle,clientes_num,clientes_piso,clientes_puerta,clientes_cp,localidades_localidades_id)VALUES("Tasia","Fernandez","666999111","C/Nueve",19,"9","5",00001,9);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Deshielo Champis","Pizza de champiñones","http://fotopizza.com/1/01.img",12.00,1);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Riada Salami","Pizza de salami","http://fotopizza.com/1/02.img",12.00,1);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Calores Diabolo","Pizza picante","http://fotopizza.com/1/03.img",10.00,2);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Playuna Anchoas","Pizza con anchoas","http://fotopizza.com/1/04.img",10.00,2);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Castañera","Pizza de castañas","http://fotopizza.com/1/05.img",8.00,3);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Hojarasca","Pizza de rúcula","http://fotopizza.com/1/06.img",11.00,3);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Helada","Pizza con hielo","http://fotopizza.com/1/07.img",3.50,4);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio,categorias_categorias_id)VALUES("1","Noel","Pizza con regalos","http://fotopizza.com/1/08.img",10.00,4);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("2","Completa","Hamburguesa completa","http://fotopizza.com/2/01.img",10.00);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("2","Bacon queso","Hamburguesa con bacon y queso","http://fotopizza.com/2/02.img",9.00);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("2","Veggie","Hamburguesa vegana","http://fotopizza.com/2/03.img",10.00);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("3","Cola","Refresco de cola","http://fotopizza.com/3/01.img",2.50);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("3","Naranja","Refresco de naranja","http://fotopizza.com/3/02.img",2.50);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("3","Limon","Refresco de limon","http://fotopizza.com/3/03.img",2.50);
INSERT INTO productos(productos_tipo, productos_nom, productos_des,productos_img,productos_precio)VALUES("3","Cerveza","Tercio o mediana","http://fotopizza.com/3/04.img",2.50);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:00:00","A",1,18.00,1,1);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:00:00","A",1,23.00,2,2);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:00:00","A",1,10.00,3,3);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:00:00","A",1,12.00,4,4);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:30:00","B",2,30.00,1,5);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:45:00","B",2,19.75,2,6);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:55:00","B",2,12.00,2,7);
INSERT INTO pedidos(pedidos_fecha,pedidos_tipo,pedidos_num,pedidos_total,tiendas_tiendas_id,clientes_clientes_id) VALUES("2021-02-01 19:57:00","B",2,33.00,1,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(1,1,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(1,2,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(2,3,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(2,4,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(9,5,2);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(12,6,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(13,6,1);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(2,7,2);
INSERT INTO pedidos_has_productos(productos_productos_id,pedidos_pedidos_id,pedidos_has_productos_num) VALUES(1,8,2);