USE pizzeria;
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Primavera",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Verano",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Otoño",1);
INSERT INTO categorias(categorias_nombre, categorias_estado) VALUES("Invierno",1);
INSERT INTO provincias(provincias_nombre) VALUES("Barcelona");
INSERT INTO provincias(provincias_nombre) VALUES("Tarragona");
INSERT INTO provincias(provincias_nombre) VALUES("Lleida");
INSERT INTO provincias(provincias_nombre) VALUES("Girona");
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Badalona",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Hospitalet",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Barcelona",1);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Reus",2);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Tarragona",2);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Lleida",3);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Balaguer",3);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Figueres",4);
INSERT INTO localidades(localidades_nombre, provincias_provincias_id) VALUES("Girona",4);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Uno",12,"1","A",00001,1);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Dos",13,"2","B",00002,2);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Tres",14,"3","B",00003,3);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Cuatro",15,"4","1",00004,4);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Cinco",16,"5","2",00005,5);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Seis",12,"6","3",00006,6);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Siete",17,"7","4",00007,7);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Ocho",18,"8","A",00008,8);
INSERT INTO direcciones(direcciones_calle, direcciones_num, direcciones_piso, direcciones_puerta, direcciones_cp,localidades_localidades_id) VALUES("C/Nueve",19,"9","5",00001,9);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Maria","Antonia Gutierrez","666111111",1);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Sera","Martin","666222111",2);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Antonio","Safore","666333111",3);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Pelusa","Gingientez","666444111",4);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Jane","Doe","666555111",5);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("John","Doe","666666111",6);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Teo","De Dios De Dios","666777111",7);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Juan","Martin","666888111",8);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Tasia","Fernandez","666999111",9);
INSERT INTO personas(personas_nombre, personas_apellidos, personas_tfno, direcciones_direcciones_id) VALUES("Anacleto","Huesped","666000111",1);